{% set name = "markupsafe" %}
{% set version = "3.0.0" %}

package:
  name: markupsafe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03ff62dea2fef3eadf2f1853bc6332bcb0458d9608b11dfb1cd5aeda1c178ea6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
  run_constrained:
    - jinja2 >=3.0.0

test:
  imports:
    - markupsafe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.palletsprojects.com/p/markupsafe
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Safely add untrusted strings to HTML/XML markup.
  description: |
    MarkupSafe implements a text object that escapes characters so it is
    safe to use in HTML and XML. Characters that have special meanings are
    replaced so that they display as the actual characters. This mitigates
    injection attacks, meaning untrusted user input can safely be displayed
    on a page.
  dev_url: https://github.com/pallets/markupsafe
  doc_url: https://markupsafe.palletsprojects.com/

extra:
  recipe-maintainers:
    - xylar
    - pelson
    - scopatz
    - ocefpaf
