{% set name = "markupsafe" %}
{% set version = "3.0.2" %}

package:
  name: markupsafe
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee55d3edf80167e48ea11a923c7386f4669df67d7994554387f84e7d8b0a2bf0

build:
  number: 1
  noarch: python  # [use_noarch]
  track_features:
    - markupsafe_no_compile    # [use_noarch]
  script:
    - sed -i.bak 's/supports_speedups = /supports_speedups = False and /g' setup.py   # [use_noarch]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform and not use_noarch]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform and not use_noarch]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python {{ python_min }}  # [use_noarch]
    - python                   # [not use_noarch]
    - pip
    - setuptools >=70.1
  run:
    - python >={{ python_min }}  # [use_noarch]
    - python                     # [not use_noarch]
  run_constrained:
    - jinja2 >=3.0.0

test:
  imports:
    - markupsafe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}  # [use_noarch]
    - python                   # [not use_noarch]

about:
  home: https://www.palletsprojects.com/p/markupsafe
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Safely add untrusted strings to HTML/XML markup.
  description: |
    MarkupSafe implements a text object that escapes characters so it is
    safe to use in HTML and XML. Characters that have special meanings are
    replaced so that they display as the actual characters. This mitigates
    injection attacks, meaning untrusted user input can safely be displayed
    on a page.
  dev_url: https://github.com/pallets/markupsafe
  doc_url: https://markupsafe.palletsprojects.com/

extra:
  recipe-maintainers:
    - xylar
    - pelson
    - scopatz
    - ocefpaf
